### ISSUE TITLE
etl processes should write logs to cloudwatch for auditing/future investigation

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/rialto-etl#212]
We can look at cloudwatch shipper: https://github.com/sul-dlss/puppet/blob/68675ba828b9b5c80587fcd5f75c14c8c8832035/modules/profile/manifests/awslogs.pp

Needs PutLogEvent https://docs.aws.amazon.com/AmazonCloudWatchLogs/latest/APIReference/API_PutLogEvents.html and DescribeLogStreams https://docs.aws.amazon.com/AmazonCloudWatchLogs/latest/APIReference/API_PutLogEvents.html (to get the sequence number)

Requires #298

**Comment by aaron-collier** [comment]
Done.
