### ISSUE TITLE
Some publications are not getting indexed.

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/rialto-etl#274]
When I run this sparql:
```
select (count(?s) as ?triples)
WHERE { ?s a <http://purl.org/ontology/bibo/Document> }
```

I get this response:
```
{
  "head" : {
    "vars" : [ "triples" ]
  },
  "results" : {
    "bindings" : [ {
      "triples" : {
        "datatype" : "http://www.w3.org/2001/XMLSchema#integer",
        "type" : "literal",
        "value" : "2665"
      }
    } ]
  }

```

which indicates there should be 2665 publications, however I'm only seeing 2011 in the webapp.  We should determine what the cause of this is (maybe a bad query in derivatives or SNS messages are getting lost)

Requires https://github.com/sul-dlss/rialto/issues/125

**Comment by justinlittman** [comment]
Perhaps https://github.com/sul-dlss/sparql-loader/issues/75

**Comment by justinlittman** [comment]
I can replicate locally.

At least some publications don't have identifiers, as indicated by:
```
select ?id
WHERE { ?id a <http://purl.org/ontology/bibo/Document> .
      MINUS { ?id <http://purl.org/ontology/bibo/identifier> ?identifier . }
      }
```
Based on similar queries, it appears that all have created and title.

**Comment by jcoyne** [comment]
The MAP indicates that publications require at least 1 identifier: https://github.com/sul-dlss/rialto/wiki/RIALTO-Data-Models-&-Profiles#publications-aka-documents-or-citations

We need to update the MAP or figure out why our data is bad.  Let's discuss with @cmh2166

**Comment by peetucket** [comment]
Blocked by #125

need more data to validate

**Comment by jcoyne** [comment]
I retested this on development and the query returns 23,659 results from Neptune and 23,302 in solr.  So we've definitely improved the percentage that get indexed.  This means that 1.5% are still missing.

**Comment by jcoyne** [comment]
Today we have 25,878 in solr and 26311 in Neptune (missing 1.65%).  I have found that a small number (378) of these documents do not have dct:title or dct:created.

**Comment by jcoyne** [comment]
Ah-ha! When I looked in the solr console, I could see that it was not "current", meaning that there were documents that had not been committed.   After committing I see 25,928 in solr.  25,928 + 378 = 26,306 which is nearly all of them.
