### ISSUE TITLE
Remove school name in parens after department name for institutes

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/rialto-etl#304]
Currently the school name is appended to department names when shown in drop-down menus and reports since there are some department names ("Dean's Office") that are ambiguous and the same across multiple schools.  However, institutes do not need this form of disambiguation and look odd when they have the school appended to them.  Discussion around this issue included having a whitelist of department names that will have the school appended, the rest would note.

Departments I've identified manually that need disambiguation (for the whitelist that will include the associated school in the parens):

* External Relations
* Administration
* Dean's Office
* Financial Aid
* Financial Aid Office
* Research Centers

**Comment by justinlittman** [comment]
closed by https://github.com/sul-dlss/rialto-etl/pull/306
