### ISSUE TITLE
Encoding issues in website display

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/rialto-etl#335]
There still appears to be encoding issues in the website -- not sure where it is coming from.

<img width="500" alt="screen shot 2018-12-12 at 11 01 34 am" src="https://user-images.githubusercontent.com/47137/49892487-f42dde00-fdfd-11e8-8add-df43d615d4d6.png">

**Comment by jcoyne** [comment]
We are able to push smart quotes through the sparql-loader and it seems to look good in neptune.

**Comment by jcoyne** [comment]
We think this is fixed by https://github.com/sul-dlss/sparql-loader/commit/92e21c3c63248da4b6aa8aeb69fdfaaa71d0af87, and all of the bad data loaded before that fix was in place.
