### ISSUE TITLE
[Discussion] Implement a pause/backup strategy to deal with SERA nightly shutdown

### ISSUE THREAD

**Issue by aaron-collier** [sul-dlss/rialto-etl#347]
Issue: The SERA API is consistently "turned off" for an extended period nightly. This causes 503 error codes to be returned for a number of hours, after which, normal service resumes and the grant extract continues. The result is an unknown number of SUNET ids that are "missed" nightly. 

Proposal: Implement a backoff strategy that would allow for extended pausing (10-30 minutes) when the result of a SERA query is a 503 error, thus not skipping any SUNET ids, but pausing any extract processing until the 503 errors stop and we can be reasonably sure normal service has resumed.

Note: this may be a 500 error or a 503 I believe by looking through honeybadger.

**Comment by justinlittman** [comment]
Basically this is what we do for WoS, so should be easy to implement for SERA.
![screen shot 2019-01-15 at 1 30 52 pm](https://user-images.githubusercontent.com/588335/51201379-e4585c80-18c9-11e9-9c15-c1017bddba3f.png)

**Comment by aaron-collier** [comment]
@justinlittman right, but I think we want, in this case, to avoid a simple retry because that causes us to essentially skip all sunets during that period of time that we know they have essentially shut down the API.

Or are you saying that in WOS those settings end up "pausing" the extract?

**Comment by mjgiarlo** [comment]
@aaron-collier We're using Faraday's built-in retry ability, which lets us retry a configurable number of times, and between each retry Faraday backs off a bit. Using our WoS strategy might be the easiest way to go.

**Comment by aaron-collier** [comment]
Thank, I think the faraday approach likely makes the most sense. This will take some refactoring around the client I think, but shouldn't be too bad.
