### ISSUE TITLE
Load SeRA data manually via CSV file

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/rialto-etl#360]
Assuming we cannot extract SeRA data from the API, can we use an Excel dump from Jan. 2019.  This would replace the extraction (but may require some rework to allow CSV instead of the format coming from the API to be used from loading)

**Comment by aaron-collier** [comment]
I have received the file from @peetucket and working on a quick extraction step using this data.

**Comment by aaron-collier** [comment]
This was done.
