### ISSUE TITLE
Investigate if institute information is in the researcher or org data coming from Profiles API

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/rialto-etl#87]

**Comment by mjgiarlo** [comment]
Here's a list of potential values we might reasonably expect to find:

* Adolescence Center
* Aging Clinical Research Center
* Alzheimer’s Research Center
* Artificial Intelligence Laboratory
* Asia-Pacific Research Center (APARC)
* Baxter Laboratory in Stem Cell Biology
* Beckman Center for Molecular and Genetic Medicine
* Behavioral Sciences, Center for Advanced Study in the
* Bill Lane Center for the American West
* Bio X
* Biodesign
* Biomedical Ethics, Center for
* Biomedical Informatics Research
* Bipolar Disorders Clinic
* Blood Center (Stanford Medical School)
* Brains in Silicon
* Brown Institute for Media Innovation
* Buddhist Studies, Ho Center for
* Cancer Center, Stanford
* Center for Spatial and Textual Analysis (CESTA)
* ChEM-H (Chemistry, Engineering & Medicine for Human Health)
* Clayman Institute for Gender Research
* Clinical Excellence Research Center (CERC)
* Comparative Studies in Race & Ethnicity
* Computer Assisted Research in the Humanities
* Computer Graphics Laboratory
* Computer Research in Music and Acoustics
* Deliberative Democracy, Center for
* Diabetes Research Center (SDRC)
* Disease Prevention, Center for Research in
* Earthquake Engineering Center (Blume)
* East Asian Studies
* Economic Policy Research, Stanford Institute for
* Education Policy Analysis, Center for (CEPA)
* Energy Modeling Forum
* Entrepreneurial Studies, Center for
* Environment, Stanford Woods Institute for
* Ethics in Society, McCoy Family Center for
* Family & Community Medicine, Center for Education & Research in
* Feldman Lab
* Freeman Spogli Institute for International Studies
* Geballe Laboratory for Advanced Materials
* Genome Technology Center
* Global Health, Center for Innovation in
* Gravity Probe-B Project
* Hansen Experimental Physics Laboratory
* Health Policy, Center for
* Hoover Institution
* Hopkins Marine Station
* Humanities Center
* Immigration Policy Lab
* Integrated Facility Engineering,  Center for
* International Conflict & Negotiation, Stanford Center on
* International Security and Cooperation, Center for  (CISAC)
* Jasper Ridge Biological Preserve
* Jewish Studies, Taube Center for
* Kavli Institute for Particle Astrophysics and Cosmology (KIPAC)
* King Research and Education Institute (Martin Luther King, Jr.)
* Language & Information, Center for Study of (CSLI)
* Language Center
* Latin American Studies
* Longevity, Stanford Center on
* Luo Lab
* Magnetic Resonance Laboratory
* Magnetic Resonance Spectroscopy and Imaging (Richard M. Lucas Center for)
* Medieval and Early Modern Studies, Center for
* Molecular and Genetic Medicine Program
* Morrison Institute for Population and Resource Studies
* Nanocharacterization Laboratory
* Nanofabrication Facility at Stanford
* Nanoscale Prototyping Laboratory
* Narcolepsy Center
* Neuroscience in Women’s Health, Center for
* Neuroscience Institute at Stanford
* Novel, Center for the Study of
* Ocean Solutions, Center for
* Patient Education Research Center
* Philanthropy & Civil Society, Stanford Center on (PACS)
* Plant Biology Department, Carnegie Institution
* Political Communication Lab
* Position, Navigation and Time, Stanford Center for
* Poverty and Inequality, Center on
* Precourt Institute for Energy
* Re-inventing the Nation’s Urban Water Infrastructure (ReNUWIt)
* Russian, East European & Eurasian Studies
* SCOPE – Stanford Center for Opportunity Policy in Education
* SLAC National Accelerator Laboratory
* Sleep Medicine Center
* Social Innovation, Center for
* Social Media Lab
* Social Sciences, Institute for Research in (IRISS)
* Spatial and Textual Analysis, Center for (CESTA)
* Spectrum (Clinical and Translational Research & Education)
* Stroke Center of Stanford
* Synchrotron Radiation Laboratory
* Systems Optimization Laboratory
* Teaching, Center to Support Excellence in (CSET)
* Technology Ventures Program, Stanford (STVP)
* Theoretical Economics, Stanford Institute for
* Theriot Lab
* TomKat Center for Sustainable Energy
* Turbulence Research, Center for
* Work, Technology and Organization, Center for

**Comment by peetucket** [comment]
looks correct, but bigger list than I was expecting, but not intractable for UI purposes...

had to look this one up based on its interesting name: http://web.stanford.edu/group/brainsinsilicon/

**Comment by mjgiarlo** [comment]
There are at least 134 centers/institutes in the org data, many of which are children of either:

1. the Inter-Departmental Programs org under the School of Humanities and Sciences; or
2. the Independent Labs, Institutes, and Centers (Dean of Research) org

**Comment by peetucket** [comment]
I think the idea was that this could be one way to connect a researcher (from the people API) to an organization (from the org API) if there wasn't an org code that be used for this purpose - but then I think @justinlittman found that org codes could be used (here #89)

**Comment by mjgiarlo** [comment]
OK, thanks, @peetucket
