### ISSUE TITLE
Implement children for org transform

### ISSUE THREAD

**Issue by justinlittman** [sul-dlss/rialto-etl#91]
The current implementation of the org transform supports parent, but does not implement mapping of children orgs.

The requirements call for:
```
Children == $.children (array of strings, identifiers for each child), mapped to OBO.BFO_0000051 for each child identifier as a child organization URI
```

**Comment by jcoyne** [comment]
Lets come to some understanding why/if we need bi-directional association before we start on this.

**Comment by justinlittman** [comment]
I'm good with that.

**Comment by justinlittman** [comment]
Not currently required.
